<?php
/** @var Eadesigndev\ComposerRepo\Block\Account\Auth $block */
?>
<table>
    <tr>
        <th class="description">Description</th>
        <th class="auth-key">Username</th>
        <th class="auth-secretkey">Password</th>
    </tr>
    <?php foreach ($block->customerKey() as $item) : ?>
        <tr>
            <td><?php echo $item->getData('description') ?></td>
            <td><?php echo $item->getData('auth_key') ?></td>
            <td><?php echo $item->getData('auth_secret') ?></td>
        </tr>
    <?php endforeach; ?>
</table>
