<?php
/** @var Eadesigndev\ComposerRepo\Block\Account\Packages $block */
/** @var Eadesigndev\ComposerRepo\Model\Packages $package */
$packages = $block->customerPackages();
/** @var \Eadesigndev\ComposerRepo\Model\Packages\VersionFiles $viewModel */
$viewModel = $block->getData('viewModel');
?>
<table>
    <tr>
        <th class="description">Order ID</th>
        <th class="package-id">Package Id</th>
        <th class="package-name">Package Name</th>
        <th class="version">Last Avaible Version</th>
    </tr>
    <?php foreach ($packages as $item) :?>
        <tr>
            <?php $package = $item->getData(\Eadesigndev\ComposerRepo\Block\Account\Packages::PACKAGE) ?>
            <td><?php echo   $item->getData('order_id') ?> </td>
            <td><?php echo   $item->getData('package_id') ?></td>
            <td><?php echo   $package->getData('name') ?></td>
            <td><?php echo   $item->getData('last_allowed_version') ?></td>
            <td><?php $viewModel->versionsByPackage($item->getData('package'))?></td>
            <td><?php //$viewModel->createTableReadyData($item->getData('package'))?></td>
        </tr>
    <?php endforeach; ?>
</table>

<div class="dashboard">
    <div class="box-account box-info">
        <div class="box-head"><h2>Installation Instructions</h2></div>
        <div class="box-content">
            To install the available packages you need to add our repository to your composer configuration with the following command:<br><br>
            <pre><code>composer config repositories.eadesignro composer <?php echo $block->repoUrl()?></code></pre>
            <br>
            Next install the package with the command:<br><br>
            <pre><code>composer require [package_name]</code></pre><br>
            When prompted, enter your <a href="https://www.eadesign.ro/composer/customer/">Authentication details</a>.
        </div>
    </div>
</div>
